fix nanomsg tag
FairRootGroup/alidist pull request #11
Opened 2018-05-25 13:09 UTC by RalfKliemt

2018-05-25 14:11 UTC, RalfKliemt commented
Also Genfit and Eigen (dependency of GenFit) are added.
I'm not sure where I got them from, but I had those lying around.

Cheers!

2018-05-25 14:55 UTC, dennisklein requested changes
Thx for the fixes and new recipes. I commented a couple of small things. Downloading the source in the build script should be avoided. AliBuild currently supports git only, find some hints on what to do in cases there is no git repo in the README file here. Thx!

2018-05-25 14:55 UTC, dennisklein commented on eigen.sh
> +#/bin/sh
Use `#!/bin/sh -e`

2018-05-25 14:55 UTC, dennisklein commented on genfit.sh
> +#!/bin.sh
Use `#!/bin/sh -e`

2018-05-25 14:55 UTC, dennisklein commented on eigen.sh
> +#fi
Lines 7-23 are working around aliBuild, you need to specify a git repo instead. In the README file in the alfadist repo you find a section on what to do when there is no git repo yet. Pls reference a git repo and remove lines 7-23. Thx!

2018-05-25 14:55 UTC, dennisklein commented on genfit.sh
> +#ROOT_ROOT
Remove this line

2018-05-25 14:55 UTC, dennisklein commented on eigen.sh
> +package: Eigen
Make sure, you match the name of the git repo exactly.

2018-05-28 07:05 UTC, RalfKliemt commented
Hi Dennis,
I implemented the requested changes. 
Cheers!
  Ralf

2018-05-28 07:52 UTC, dennisklein approved these changes

2018-05-28 08:00 UTC, dennisklein commented
Contains fix for #10

2018-05-28 08:58 UTC, fuhlig1 approved these changes

2018-05-28 08:58 UTC, merged